source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-assetpack'
gem 'sinatra-websocket'
gem 'coffee-script'
gem 'spotify'
gem 'plaything'
gem 'haml'
gem 'rake'
gem 'sass'
gem 'thin'
gem 'aescrypt'
gem 'main'
gem 'rest-client'
gem 'sqlite3'

group :test do
  gem 'pry'
  gem 'pry-debugger'
  gem 'autotest-standalone'
  gem 'autotest-growl'
  gem 'rspec'
  gem 'codeclimate-test-reporter'
  gem 'cucumber'
  gem 'watir'
  gem 'watir-webdriver'
  gem 'jasmine'
  gem 'rack-asset-compiler'
end
