source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'sinatra-websocket'
gem 'spotify'
gem 'plaything'
gem 'haml'
gem 'rake'
gem 'sass'
gem 'thin'
gem 'aescrypt'
gem 'main'
gem 'rest-client'
gem 'sqlite3'
gem 'require_all'

group :test do
  gem 'pry'
  gem 'autotest-standalone'
  gem 'autotest-growl'
  gem 'rspec'
  gem 'codeclimate-test-reporter'
  gem 'cucumber'
  gem 'watir', '5.0.0'
  gem 'watir-webdriver', '0.9.3'
  gem 'rack-asset-compiler'
  gem 'rubocop'
  gem 'rack-test', require: 'rack/test'
  gem 'climate_control'
end
