source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'sinatra-websocket'
gem 'rspotify'
gem 'haml'
gem 'rake'
gem 'sass'
gem 'thin'
gem 'aescrypt'
gem 'main'
gem 'rest-client'
gem 'sqlite3'
gem 'require_all'
gem 'foreman'
gem 'jbuilder'
gem 'tilt-jbuilder'

group :test do
  gem 'pry'
  gem 'rb-readline'
  gem 'rspec'
  gem 'webmock'
  gem 'codeclimate-test-reporter'
  gem 'rack-asset-compiler'
  gem 'rubocop'
  gem 'rack-test', require: 'rack/test'
  gem 'climate_control'
end
